### ISSUE TITLE
runtime plugin can cause deprecation warnings on Gradle 5.1

### ISSUE THREAD

**Issue by shollander** [beryx/badass-runtime-plugin#4]
Given the following in a `build.gradle` file with the `org.beryx.runtime` plugin applied:

```
buildscript {
    ext {
        myStuff = [
            [someName: "value1"],
            [someName: "value2"]
        ]
    }
}
```

A deprecation warning with the following stacktrace is created by Gradle (only when the `org.beryx.runtime` plugin is applied). (Run `gradle help --warning-mode all --stackrace` to show.)

```
Using method ObjectFactory.property() method to create a property of type Map<K, V> has been deprecated. This wil fail with an error in Gradle 6.0. Please use ObjectFactory.mapProperty() instead.
    at org.gradle.api.internal.model.DefaultObjectFactory.property(DefaultObjectFactory.java:111)
    at org.beryx.runtime.data.RuntimePluginExtension.<init>(RuntimePluginExtension.groovy:59)
    at org.beryx.runtime.data.RuntimePluginExtension_Decorated.<init>(Unknown Source)
```

**Comment by siordache** [comment]
Fixed in 1.1.3.
