### ISSUE TITLE
Apache POI Error when opening Excel File while running jlink image

### ISSUE THREAD

**Issue by Tonne-TM** [beryx/badass-runtime-plugin#44]
I got a rather special bug. The following line is causing an error when executed in the generated jlink image on windows (10). When I start the programm as normal jar with Java 11 there is no error when executing this line with the same Input.  
(This line is used to read an excel file)

## Line
```java
import org.apache.poi.ss.usermodel.*;
...
Workbook workbook = WorkbookFactory.create(file)
```
## Error when running jlink image
```
java.io.IOException
        at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:351)
        at org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:314)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:302)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:271)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:252)
        at de.name.excelimporter.importer.excel.ExcelReader.<init>(ExcelReader.java:41)
        at de.name.excelimporter.importer.Importer.lambda$importExcel$20(Importer.java:149)
        at de.name.excelimporter.importer.Importer$$Lambda$584.00000000E24E6AF0.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.ExceptionInInitializerError
        at java.base/java.lang.J9VMInternals.ensureError(J9VMInternals.java:193)
        at java.base/java.lang.J9VMInternals.recordInitializationFailure(J9VMInternals.java:182)
        at org.apache.poi.ss.util.CellReference.<init>(CellReference.java:109)
        at org.apache.poi.xssf.usermodel.XSSFCell.<init>(XSSFCell.java:118)
        at org.apache.poi.xssf.usermodel.XSSFRow.<init>(XSSFRow.java:75)
        at org.apache.poi.xssf.usermodel.XSSFSheet.initRows(XSSFSheet.java:268)
        at org.apache.poi.xssf.usermodel.XSSFSheet.read(XSSFSheet.java:231)
        at org.apache.poi.xssf.usermodel.XSSFSheet.onDocumentRead(XSSFSheet.java:218)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.parseSheet(XSSFWorkbook.java:448)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:413)
        at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:184)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:282)
        at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:88)
        at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:116)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:339)
        at org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:314)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:302)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:271)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:252)
        at de.name.excelimporter.importer.excel.ExcelReader.<init>(ExcelReader.java:41)
        at de.name.excelimporter.importer.Importer.lambda$importExcel$20(Importer.java:149)
        at de.name.excelimporter.importer.Importer$$Lambda$584.00000000E24E6AF0.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.nio.charset.UnsupportedCharsetException: Big5
        at java.base/java.nio.charset.Charset.forName(Charset.java:529)
        at org.apache.poi.util.StringUtil.<clinit>(StringUtil.java:39)
        at org.apache.poi.ss.util.CellReference.<init>(CellReference.java:109)
        at org.apache.poi.xssf.usermodel.XSSFCell.<init>(XSSFCell.java:118)
        at org.apache.poi.xssf.usermodel.XSSFRow.<init>(XSSFRow.java:75)
        at org.apache.poi.xssf.usermodel.XSSFSheet.initRows(XSSFSheet.java:268)
        at org.apache.poi.xssf.usermodel.XSSFSheet.read(XSSFSheet.java:231)
        at org.apache.poi.xssf.usermodel.XSSFSheet.onDocumentRead(XSSFSheet.java:218)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.parseSheet(XSSFWorkbook.java:448)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.onDocumentRead(XSSFWorkbook.java:413)
        at org.apache.poi.ooxml.POIXMLDocument.load(POIXMLDocument.java:184)
        at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:282)
        at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:88)
        at org.apache.poi.xssf.usermodel.XSSFWorkbookFactory.createWorkbook(XSSFWorkbookFactory.java:116)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.poi.ss.usermodel.WorkbookFactory.createWorkbook(WorkbookFactory.java:339)
        at org.apache.poi.ss.usermodel.WorkbookFactory.createXSSFWorkbook(WorkbookFactory.java:314)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:302)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:271)
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:252)
        at de.name.excelimporter.importer.excel.ExcelReader.<init>(ExcelReader.java:41)
        at de.name.excelimporter.importer.Importer.lambda$importExcel$20(Importer.java:149)
        at de.name.excelimporter.importer.Importer$$Lambda$584.00000000E24E6AF0.run(Unknown Source)
        at java.base/java.lang.Thread.run(Thread.java:831)

```

## Parts of build.gradle
```groovy
plugins {
    id 'java'
    id 'idea'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.8'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
    id 'org.beryx.runtime' version '1.7.3'
}

dependencies {
    compile('org.xerial:sqlite-jdbc:3.28.0')

    //Excel Read Apache POI
    compile group: 'org.apache.poi', name: 'poi', version: '4.1.0'
    compile group: 'org.apache.poi', name: 'poi-ooxml', version: '4.1.0'

    //logger slf4j
    compile group: 'org.slf4j', name: 'slf4j-log4j12', version: '1.7.26'

    //tiny log
    compile group: 'org.tinylog', name: 'tinylog-api', version: '2.0.0'
    compile group: 'org.tinylog', name: 'tinylog-impl', version: '2.0.0'

    compile group: 'org.jdom', name: 'jdom2', version: '2.0.6'

    compile group: 'io.github.java-diff-utils', name: 'java-diff-utils', version: '2.2.0'
    compile group: 'org.fxmisc.richtext', name: 'richtextfx', version: '0.10.1'
    compile group: 'org.xmlunit', name: 'xmlunit-core', version: '2.6.3'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

javafx {
    modules = ['javafx.controls', 'javafx.fxml']
    version = "11.0.2"
}

runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
}

jar {
    manifest {
        attributes "Main-Class": "$mainClassName"
    }
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

**Comment by siordache** [comment]
Not sutre if it helps, but try adding the `jdk.charsets` module:

```
runtime {
    ...
    modules.add 'jdk.charsets'
}
```

**Comment by Tonne-TM** [comment]
I also experience the initial error when using a modular version of my project with the badass-jlink plugin to build an image.

**Comment by siordache** [comment]
Replace the added line with this one:
```
    modules.addAll 'jdk.charsets', 'java.xml'
```

**Comment by siordache** [comment]
For the modular version with the badass-jlink plugin you can try something like this::
```
jlink {
    ...
    mergedModule {
        additive = true
        requires 'jdk.charsets''
        requires 'java.xml''
    }
}
```

Alternatively, with both plugins you can try passing the `--bind-services` option to jlink:
```
runtime { // or jlink
    options = ['--bind-services', ...]
}
```
However, keep in mind that using `--bind-services` you may [end up with some unnecessary modules](https://stackoverflow.com/questions/48468111/jlink-service-binding-links-many-unnecessary-modules) in your runtime image.

**Comment by Tonne-TM** [comment]
>     modules.addAll 'jdk.charsets', 'java.xml'
This also did not work. I get the same error at  start as without the java.xml. (Also the image is 12mb smaller in comparison without this line)

>     options = ['--bind-services', ...]
This did work (Thanks!) but it added additional 25mb to the image.

Is there a way to figure out what modules I am exactly missing?

**Comment by siordache** [comment]
I was wrong. If you use `modules.add()` or `modules.addAll()`, the plugin no longer tries to figure out which modules are required by your application, so you end up with only the added modules. Here's what you need to do:


**Solution 1 (old style)**
Configure the `modules` property with `jdk.charsets` and the modules suggested by the `suggestModules` task:

```
runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    modules = ['jdk.charsets', ... /* put here all modules suggested by the suggestModules task */]
}
```

**Solution 2 (new style)**
In release 1.8.0 I introduced the `additive` property, which is similar to the one available for the badass-jlink plugin:

```
runtime {
    options = ['--strip-debug', '--compress', '2', '--no-header-files', '--no-man-pages']
    additive = true
    modules = ['jdk.charsets']
}
```


It's still possible that the resulting image is the same size as the one obtained using `--bind-services`. If this is the case, it means that `--bind-services` didn't add any unnecessary modules. It's not a bug.

**Comment by Tonne-TM** [comment]
**Thank you very much!** This solved my problem and the image is now also smaller again!

**Comment by MinglangTuo** [comment]
How to add '''modules.addAll 'jdk.charsets', 'java.xml''' in maven?
