### ISSUE TITLE
Setting installerOutputDir only producers a single installer

### ISSUE THREAD

**Issue by JamzTheMan** [beryx/badass-runtime-plugin#54]
If I set installerOutputDir, e.g. `installerOutputDir = file("releases")` and run jpackage under Windows 10, using JDK14, gradle 6.3, it only produces an .msi package.

Expected results: .exe and .msi packages

Commenting out `installerOutputDir` and using ` outputDir` instead I get both installers. 

*note: `installerType`  is not being set/used

**Comment by siordache** [comment]
Fixed in 1.8.3.

**Comment by JamzTheMan** [comment]
@siordache Sorry but got another use case for you :)

The above works now unless you now also add `'--temp', 'releases/temp-files',` as an `installerOptions` I assume when it's time to create the .msi it's running the command again and wants a clean temp dir.

```jdk.incubator.jpackage.internal.PackagerException: Error: temp (releases/temp-files) must be non-existant or empty directory
        at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.DeployParams.validate(DeployParams.java:261)
        at jdk.incubator.jpackage/jdk.incubator.jpackage.internal.Arguments.processArguments(Arguments.java:486)
        at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.execute(Main.java:97)
        at jdk.incubator.jpackage/jdk.incubator.jpackage.main.Main.main(Main.java:51)

```

**Comment by siordache** [comment]
Try it again with 1.8.4. It should work now.

**Comment by JamzTheMan** [comment]
Awesome, worked like a charm now. thanks!
