### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by danielpeintner** [beryx/badass-runtime-plugin#86]
I am using the plugin with Java11 runtime by calling `jpackage` with jdk-16 without any issues.

To be prepared for future updates I tried to use jdk-16 for runtime and building.
* `gradlew run` //  works fine, I can do what I could do before
* `gradlew jpackage` // works also fine, at least it creates the executable.

The issue I am running into is that launching the application with the created jpackage executable it fails to use SSL properly (connecting the same Google appspot server). This happens on *all* 3 platforms, namely Windows, Mac and Linux.

```
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
	at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
```

I am not sure if this is the right place to ask.  It looks like somehow certificates are missing in the produced jpackage build. Whether that has to do with the plugin, jpackage or a missing dependency that is needed for recent JDKs I am not sure. I just know a simple `gradlew run` works.

Did anyone experience similar issues? 

Any helps or pointer is appreciated.
Thanks!

**Comment by siordache** [comment]
Does adding `jdk.crypto.ec` help?
```
runtime {
    modules = ['jdk.crypto.ec', ...]
    ...
}
```

**Comment by danielpeintner** [comment]
Yes, that did the trick.
Not sure "why" in Java11 this is not necessary..

Thank you very much!
